### ISSUE TITLE
how to run inpainting.m

### ISSUE THREAD

**Issue by NerminSalem** [ikuwow/inpainting_criminisi2004#3]
hi
i tried [inpainted,c,v,mov] = inpainting(imread('lena.bmp'), 1, 5);
but got this error?
Error using gradient (line 49)
Too many output arguments.
can u help? @ikuwow , thanks

**Comment by aaathi** [comment]
Hi,
I tried running this program, but always showing errors such as ' not enough input arguments '. How to solve this problem.
